<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Http\Request;
use App\Models\City;
use DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('cities')->delete();
        

        $cities4 = array(
            array('name' => "Beitar illit" , 'short_name' => "beitar-illit"),
            array('name' => "Bethlehem" , 'short_name' => "bethlehem"),
            array('name' => "Caesarea" , 'short_name' => "caesarea"),
            array('name' => "Petach Tikva" , 'short_name' => "petach-tikva" ),
            array('name' => "Ramallah" , 'short_name' => "ramallah" ),
            array('name' => "Gaza" , 'short_name' => "gaza"),
            array('name' => "'Arad" , 'short_name' => "arad"),
            array('name' => "'Omer" , 'short_name' => "omer"),
            array('name' => "Ashdod" , 'short_name' => "ashdod"),
            array('name' => "Ashqelon" , 'short_name' => "ashqelon"),
            array('name' => "Be'er Sheva" , 'short_name' => "be-er-sheva"),
            array('name' => "Beersheba" , 'short_name' => "beersheba"),
            array('name' => "Bene Ayish" , 'short_name' => "bene-ayish"),
            array('name' => "Dimona" , 'short_name' => "dimona"),
            array('name' => "Elat" , 'short_name' => "elat"),
            array('name' => "Gan Yavne" , 'short_name' => "gan-yavne"),
            array('name' => "Nahal `Oz", 'short_name' => "nahal-Oz"),
            array('name' => "Netivot", 'short_name' => "netivot"),
            array('name' => "Ofaqim", 'short_name' => "ofaqim"),
            array('name' => "Qiryat Gat", 'short_name' => "qiryat-gat"),
            array('name' => "Qiryat Mal'akhi", 'short_name' => "qiryat-mal-akhi"),
            array('name' => "Sederot", 'short_name' => "sederot"),
            array('name' => "Yeroham", 'short_name' => "yeroham"),
            array('name' => "kiryat Malachi", 'short_name' => "kiryat-malachi"),
            array('name' => "Be'er Ya'aqov" , 'short_name' => "Be-er-Ya-aqov"),
            array('name' => "Beit Shemesh" , 'short_name' => "beit-shemesh"),
            array('name' => "Bene Beraq" , 'short_name' => "bene-beraq"),
            array('name' => "Bnei Brak" , 'short_name' => "bnei-brak"),
            array('name' => "Even Yehuda" , 'short_name' => "even-yehuda"),
            array('name' => "Fureidis", 'short_name' => "fureidis" ),
            array('name' => "Gat Rimon" , 'short_name' => "gat-rimon"),
            array('name' => "Gedera" , 'short_name' => "gedera"),
            array('name' => "Givat Shmuel" , 'short_name' => "givat-shmuel"),
            array('name' => "Hibat Zion" , 'short_name' => "hibat-zion"),
            array('name' => "Hod HaSharon" , 'short_name' => "hod-haSharon"),
            array('name' => "Hogar" , 'short_name' => "hogar"),
            array('name' => "Jaljulye" , 'short_name' => "jaljulye"),
            array('name' => "Jatt" , 'short_name' => "jatt"),
            array('name' => "Kafar Qasem" , 'short_name' => "kafar-qasem"),
            array('name' => "Kefar Sava" , 'short_name' => "kefar-sava"),
            array('name' => "Kefar Yona" , 'short_name' => "kefar-yona"),
            array('name' => "Kfar Saba" , 'short_name' => "kfar-saba"),
            array('name' => "Kiryag Bialik" , 'short_name' => "kiryag-bialik"),
            array('name' => "Lod" , 'short_name' => "lod"),
            array('name' => "Mazkeret Batya" , 'short_name' => "mazkeret-batya"),
            array('name' => "Modi'in" , 'short_name' => "modi-in"),
            array('name' => "Nes Ziyyona" , 'short_name' => "nes-ziyyona"),
            array('name' => "Ness Ziona" , 'short_name' => "ness-ziona"),
            array('name' => "Netanya", 'short_name' => "netanya" ),
            array('name' => "Nordiya" , 'short_name' => "nordiya"),
            array('name' => "Pardesiyya", 'short_name' => "pardesiyya" ),
            array('name' => "Petakh Tiqwa", 'short_name' => "petakh-tiqwa" ),
            array('name' => "Qadima", 'short_name' => "qadima" ),
            array('name' => "Qalansawe", 'short_name' => "qalansawe" ),
            array('name' => "Qiryat 'Eqron", 'short_name' => "qiryat-eqron" ),
            array('name' => "Ra'anana", 'short_name' => "ra-anana" ),
            array('name' => "Ramla", 'short_name' => "ramla" ),
            array('name' => "Rehovot", 'short_name' => "rehovot" ),
            array('name' => "Rekhovot" , 'short_name' => "rekhovot"),
            array('name' => "Rinnatya" , 'short_name' => "rinnatya"),
            array('name' => "Rishon LeZiyyon" , 'short_name' => "rishon-leziyyon"),
            array('name' => "Rosh HaAyin" , 'short_name' => "rosh-haayin"),
            array('name' => "Shoham" , 'short_name' => "shoham"),
            array('name' => "Tayibe" , 'short_name' => "tayibe"),
            array('name' => "Tire" , 'short_name' => "tire"),
            array('name' => "Tsur Igal" , 'short_name' => "tsur-igal"),
            array('name' => "Udim" , 'short_name' => "udim"),
            array('name' => "Yavne" , 'short_name' => "yavne"),
            array('name' => "Yehud" , 'short_name' => "yehud"),
            array('name' => "'Afula" , 'short_name' => "afula"),
            array('name' => "'Akko" , 'short_name' => "akko"),
            array('name' => "'Arrabe" , 'short_name' => "arrabe"),
            array('name' => "'Ein Mahel" , 'short_name' => "ein-mahel"),
            array('name' => "'Ilut" , 'short_name' => "ilut"),
            array('name' => "Abu Sinan" , 'short_name' => "abu-sinan"),
            array('name' => "Basmat Tab'un" , 'short_name' => "basmat-tab-un"),
            array('name' => "Beit Jann" , 'short_name' => "beit-jann"),
            array('name' => "Bet She'an" , 'short_name' => "bet-she-an"),
            array('name' => "Bi'ne" , 'short_name' => "bi-ne"),
            array('name' => "Bir-al-Maksur" , 'short_name' => "bir-al-maksur"),
            array('name' => "Bu'eine-Nujeidat" , 'short_name' => "Bu-eine-nujeidat"),
            array('name' => "Dabburye" , 'short_name' => "dabburye"),
            array('name' => "Dayr Hannah" , 'short_name' => "dayr-hannah"),
            array('name' => "Dayr-al-Asad" , 'short_name' => "dayr-al-asad"),
            array('name' => "Hazor HaGelilit" , 'short_name' => "hazor-haGelilit"),
            array('name' => "I'billin" , 'short_name' => "i-billin"),
            array('name' => "Iksal" , 'short_name' => "iksal"),
            array('name' => "Judeide-Maker" , 'short_name' => "judeide-maker"),
            array('name' => "Kabul" , 'short_name' => "kabul"),
            array('name' => "Kafar Kanna" , 'short_name' => "kafar-kanna"),
            array('name' => "Kafar Manda" , 'short_name' => "kafar-manda"),
            array('name' => "Kafar Yasif" , 'short_name' => "kafar-yasif"),
            array('name' => "Karmiel" , 'short_name' => "karmiel"),
            array('name' => "Kisra-Sumei" , 'short_name' => "kisra-sumei"),
            array('name' => "Ma'alot Tarshikha" , 'short_name' => "Ma-alot-tarshikha"),
            array('name' => "Majd-al-Kurum" , 'short_name' => "majd-al-kurum"),
            array('name' => "Migdal Ha'Emeq" , 'short_name' => "migdal-ha-emeq"),
            array('name' => "Mugar" , 'short_name' => "mugar"),
            array('name' => "Nahariyya" , 'short_name' => "nahariyya"),
            array('name' => "Nahef" , 'short_name' => "nahef"),
            array('name' => "Nazerat" , 'short_name' => "nazerat"),
            array('name' => "Nazerat 'Illit" , 'short_name' => "nazerat-illit"),
            array('name' => "Qiryat Shemona" , 'short_name' => "qiryat-shemona"),
            array('name' => "Qiryat Tiv'on" , 'short_name' => "qiryat-tiv-on"),
            array('name' => "Rame" , 'short_name' => "rame"),
            array('name' => "Reine" , 'short_name' => "reine"),
            array('name' => "Sakhnin" , 'short_name' => "sakhnin"),
            array('name' => "Shefar'am" , 'short_name' => "shefar-am"),
            array('name' => "Tamra" , 'short_name' => "tamra"),
            array('name' => "Tiberias" , 'short_name' => "tiberias"),
            array('name' => "Tur'an" , 'short_name' => "tur-an"),
            array('name' => "Yirka" , 'short_name' => "yirka"),
            array('name' => "Yoqne'am Illit" , 'short_name' => "yoqne-am-illit"),
            array('name' => "Zefat" , 'short_name' => "zefat"),
            array('name' => "Zur Yigal" , 'short_name' => "zur-yigal"),
            array('name' => "Hebron" , 'short_name' => "hebron"),
            array('name' => "Sgula", 'short_name' => "sgula"),
            array('name' => "Jerusalem", 'short_name' => "jerusalem"),
            array('name' => "'Ar'ara" , 'short_name' => "Ar-ara"),
            array('name' => "'Isifya" , 'short_name' => "Isifya"),
            array('name' => "Baqa al-Gharbiyyah" , 'short_name' => "baqa-al-gharbiyyah"),
            array('name' => "Binyamina" , 'short_name' => "binyamina"),
            array('name' => "Daliyat-al-Karmil" , 'short_name' => "daliyat-al-karmil"),
            array('name' => "Jizr-az-Zarqa" , 'short_name' => "jizr-az-zarqa"),
            array('name' => "Khadera" , 'short_name' => "khadera"),
            array('name' => "Khefa" , 'short_name' => "khefa"),
            array('name' => "Nesher" , 'short_name' => "nesher"),
            array('name' => "Or 'Aqiva" , 'short_name' => "or-aqiva"),
            array('name' => "Pardes Khanna-Karkur" , 'short_name' => "pardes-khanna-karkur"),
            array('name' => "Qiryat Atta" , 'short_name' => "qiryat-atta"),
            array('name' => "Qiryat Bialik" , 'short_name' => "qiryat-bialik"),
            array('name' => "Qiryat Motzkin" , 'short_name' => "qiryat-motzkin"),
            array('name' => "Qiryat Yam" , 'short_name' => "qiryat-yam"),
            array('name' => "Rekhasim" , 'short_name' => "rekhasim"),
            array('name' => "Tirat Karmel" , 'short_name' => "tirat-karmel"),
            array('name' => "Umm-al-Fahm" , 'short_name' => "umm-al-fahm"),
            array('name' => "Zikhron Ya'aqov" , 'short_name' => "zikhron-ya-aqov"),
            array('name' => "Qalqilya", 'short_name' => "qalqilya"),
            array('name' => "Hadera", 'short_name' => "hadera"),
            array('name' => "Kiryag Bialik", 'short_name' => "kiryag-bialik"),
            array('name' => "Bet Shemesh", 'short_name' => "bet-shemesh"),
            array('name' => "Mevasserat Ziyyon", 'short_name' => "mevasserat-ziyyon"),
            array('name' => "Yerushalayim" , 'short_name' => "yerushalayim"),
            
            

        );

        \DB::table('cities')->insert($cities4);

    }
}
