<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Http\Request;
use App\Models\City;
use DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('cities')->delete();
        

        $cities4 = array(
            
            array('name' => "Bethlehem"),
            array('name' => "Caesarea"),
            array('name' => "Petach Tikva" ),
            array('name' => "Ramallah" ),
            array('name' => "Gaza"),
            array('name' => "'Arad"),
            array('name' => "'Omer"),
            array('name' => "Ashdod"),
            array('name' => "Ashqelon"),
            array('name' => "Be'er Sheva"),
            array('name' => "Beersheba"),
            array('name' => "Bene Ayish"),
            array('name' => "Dimona"),
            array('name' => "Elat"),
            array('name' => "Gan Yavne"),
            array('name' => "Nahal `Oz"),
            array('name' => "Netivot"),
            array('name' => "Ofaqim"),
            array('name' => "Qiryat Gat"),
            array('name' => "Qiryat Mal'akhi"),
            array('name' => "Sederot"),
            array('name' => "Yeroham"),
            array('name' => "kiryat Malachi"),
            array('name' => "Be'er Ya'aqov" ),
            array('name' => "Beit Shemesh" ),
            array('name' => "Bene Beraq" ),
            array('name' => "Bnei Brak" ),
            array('name' => "Even Yehuda" ),
            array('name' => "Fureidis" ),
            array('name' => "Gat Rimon" ),
            array('name' => "Gedera" ),
            array('name' => "Givat Shmuel" ),
            array('name' => "Hibat Zion" ),
            array('name' => "Hod HaSharon" ),
            array('name' => "Hogar" ),
            array('name' => "Jaljulye" ),
            array('name' => "Jatt" ),
            array('name' => "Kafar Qasem" ),
            array('name' => "Kefar Sava" ),
            array('name' => "Kefar Yona" ),
            array('name' => "Kfar Saba" ),
            array('name' => "Kiryag Bialik" ),
            array('name' => "Lod" ),
            array('name' => "Mazkeret Batya" ),
            array('name' => "Modi'in" ),
            array('name' => "Nes Ziyyona" ),
            array('name' => "Ness Ziona" ),
            array('name' => "Netanya" ),
            array('name' => "Nordiya" ),
            array('name' => "Pardesiyya" ),
            array('name' => "Petakh Tiqwa" ),
            array('name' => "Qadima" ),
            array('name' => "Qalansawe" ),
            array('name' => "Qiryat 'Eqron" ),
            array('name' => "Ra'anana" ),
            array('name' => "Ramla" ),
            array('name' => "Rehovot" ),
            array('name' => "Rekhovot" ),
            array('name' => "Rinnatya" ),
            array('name' => "Rishon LeZiyyon" ),
            array('name' => "Rosh HaAyin" ),
            array('name' => "Shoham" ),
            array('name' => "Tayibe" ),
            array('name' => "Tire" ),
            array('name' => "Tsur Igal" ),
            array('name' => "Udim" ),
            array('name' => "Yavne" ),
            array('name' => "Yehud" ),
            array('name' => "'Afula" ),
            array('name' => "'Akko" ),
            array('name' => "'Arrabe" ),
            array('name' => "'Ein Mahel" ),
            array('name' => "'Ilut" ),
            array('name' => "Abu Sinan" ),
            array('name' => "Basmat Tab'un" ),
            array('name' => "Beit Jann" ),
            array('name' => "Bet She'an" ),
            array('name' => "Bi'ne" ),
            array('name' => "Bir-al-Maksur" ),
            array('name' => "Bu'eine-Nujeidat" ),
            array('name' => "Dabburye" ),
            array('name' => "Dayr Hannah" ),
            array('name' => "Dayr-al-Asad" ),
            array('name' => "Hazor HaGelilit" ),
            array('name' => "I'billin" ),
            array('name' => "Iksal" ),
            array('name' => "Judeide-Maker" ),
            array('name' => "Kabul" ),
            array('name' => "Kafar Kanna" ),
            array('name' => "Kafar Manda" ),
            array('name' => "Kafar Yasif" ),
            array('name' => "Karmiel" ),
            array('name' => "Kisra-Sumei" ),
            array('name' => "Ma'alot Tarshikha" ),
            array('name' => "Majd-al-Kurum" ),
            array('name' => "Migdal Ha'Emeq" ),
            array('name' => "Mugar" ),
            array('name' => "Nahariyya" ),
            array('name' => "Nahef" ),
            array('name' => "Nazerat" ),
            array('name' => "Nazerat 'Illit" ),
            array('name' => "Qiryat Shemona" ),
            array('name' => "Qiryat Tiv'on" ),
            array('name' => "Rame" ),
            array('name' => "Reine" ),
            array('name' => "Sakhnin" ),
            array('name' => "Shefar'am" ),
            array('name' => "Tamra" ),
            array('name' => "Tiberias" ),
            array('name' => "Tur'an" ),
            array('name' => "Yirka" ),
            array('name' => "Yoqne'am Illit" ),
            array('name' => "Zefat" ),
            array('name' => "Zur Yigal" ),
            array('name' => "Hebron" ),
            array('name' => "Sgula"),
            array('name' => "Jerusalem"),
            array('name' => "'Ar'ara" ),
            array('name' => "'Isifya" ),
            array('name' => "Baqa al-Gharbiyyah" ),
            array('name' => "Binyamina" ),
            array('name' => "Daliyat-al-Karmil" ),
            array('name' => "Jizr-az-Zarqa" ),
            array('name' => "Khadera" ),
            array('name' => "Khefa" ),
            array('name' => "Nesher" ),
            array('name' => "Or 'Aqiva" ),
            array('name' => "Pardes Khanna-Karkur" ),
            array('name' => "Qiryat Atta" ),
            array('name' => "Qiryat Bialik" ),
            array('name' => "Qiryat Motzkin" ),
            array('name' => "Qiryat Yam" ),
            array('name' => "Rekhasim" ),
            array('name' => "Tirat Karmel" ),
            array('name' => "Umm-al-Fahm" ),
            array('name' => "Zikhron Ya'aqov" ),
            array('name' => "Qalqilya"),
            array('name' => "Hadera"),
            array('name' => "Kiryag Bialik"),
            array('name' => "Bet Shemesh"),
            array('name' => "Mevasserat Ziyyon"),
            array('name' => "Yerushalayim"),
            

        );

        \DB::table('cities')->insert($cities4);

    }
}
